general {
    lock_cmd = /home/bo7afes/.local/share/quickshell-lockscreen/lock.sh
    after_sleep_cmd = /home/bo7afes/.local/share/quickshell-lockscreen/lock.sh && hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
listener {
    timeout = 600          # 10 minutes
    on-timeout = ~/skripts/safe-suspend.sh
}
